# Paquetes en Python

## Como importar paquetes




In [3]:
import numpy as np

In [4]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Cargar funciones de un paquete

In [5]:
from numpy import arange

In [6]:
arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Funciones y metodos

In [7]:
A = np.arange(9)

In [8]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
type(A)

numpy.ndarray

In [10]:
# Calculando promedio con funcion numpy

np.mean(A)

4.0

In [11]:
# Calculando promedio con metodo de objeto

A.mean()

4.0

In [12]:
# Transformando arreglo con funcion de numpy

np.reshape(A, (3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
# Tranformando arreglo con metodo de objeto

A.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])